version: '3'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - app_network
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes_from:
            - php
        ports:
            - 80:80
        depends_on:
            - php
            - database
        networks:
            - app_network
    database:
        image: mysql:8.0.25
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - app_network

volumes:
    mysql:

networks:
    app_network:
